/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html", "./src/**/*.js"],
  theme: {
      extend: {
        colors: {
          "on-primary-container": "#330066",
          "on-secondary-fixed-variant": "#00615c",
          "primary-dim": "#9547f7",
          "on-surface-variant": "#a3aac4",
          "surface-container-highest": "#192540",
          "secondary": "#3ff2e6",
          "tertiary-container": "#f0abfc",
          "surface-dim": "#060e20",
          "inverse-surface": "#faf8ff",
          "on-secondary": "#005652",
          "on-background": "#dee5ff",
          "tertiary": "#f7bfff",
          "surface-container-high": "#141f38",
          "secondary-fixed": "#3ff2e6",
          "tertiary-fixed-dim": "#e29eee",
          "inverse-on-surface": "#4d556b",
          "background": "#060e20",
          "tertiary-fixed": "#f0abfc",
          "surface-container-low": "#091328",
          "on-primary-fixed-variant": "#3f007c",
          "on-surface": "#dee5ff",
          "surface-container": "#0f1930",
          "surface-variant": "#192540",
          "primary-container": "#ba88ff",
          "primary-fixed": "#ba88ff",
          "on-tertiary-fixed": "#470d56",
          "outline": "#6d758c",
          "surface": "#060e20",
          "inverse-primary": "#7e29df",
          "secondary-dim": "#23e3d8",
          "tertiary-dim": "#e29eee",
          "surface-bright": "#1f2b49",
          "on-tertiary-container": "#5e266d",
          "error-dim": "#d73357",
          "on-tertiary": "#682f77",
          "primary": "#c59aff",
          "on-primary": "#420082",
          "on-error": "#490013",
          "error-container": "#a70138",
          "secondary-container": "#006a64",
          "surface-tint": "#c59aff",
          "surface-container-lowest": "#000000",
          "on-secondary-container": "#dbfffa",
          "on-primary-fixed": "#000000",
          "on-error-container": "#ffb2b9",
          "on-secondary-fixed": "#00423e",
          "on-tertiary-fixed-variant": "#682f76",
          "outline-variant": "#40485d",
          "primary-fixed-dim": "#b075ff",
          "error": "#ff6e84"
        },
        fontFamily: {
          "headline": ["Newsreader"],
          "body": ["Manrope"],
          "label": ["Manrope"]
        },
        borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
        spacing: {
          '8': '8px', '16': '16px', '24': '24px', '32': '32px',
          '40': '40px', '48': '48px', '56': '56px', '64': '64px',
          '72': '72px', '80': '80px',
        }
      },
    },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
